Update .husky/pre-commit
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,6 @@
-npm run build && git add dist/
+npm run build
+if [ $? -ne 0 ]; then
+  echo "Build failed. Commit prevented."
+  exit 1
+fi
+git add dist/
